name: Java Selenium Enterprise Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Java 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
        
    - name: Install Google Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        
    - name: Execute Tests (Maven & TestNG)
      working-directory: ./civifix-java-automation
      run: mvn clean test
        
    - name: Upload Passed Execution Report
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: Passed-Execution-Report
        path: civifix-java-automation/Passed_Execution_Report_*.xlsx
        
    - name: Upload Failed Execution Report
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: Failed-Execution-Report
        path: civifix-java-automation/Failed_Execution_Report_*.xlsx
